### ISSUE TITLE
Help: What is it?

### ISSUE THREAD

**Issue by sja** [indutny/vock#5]
Sorry, but I did not get (event by RTFM) what vock and it's server does!
Is it something like a Audio transportation lib/framework to connect SoundInputDevice on Host X to SoundOutputDevice on Host Y?
Or is it like a voice chat?

I'm looking for a VoIP client for dialplan unit test purposes a SIP Server. (Asterisk)

**Comment by indutny** [comment]
Its a voice chat, and not really a module.

**Comment by sja** [comment]
Ah, got it. Thank you.
